DROP TABLE IF EXISTS students;
CREATE TABLE students (
    id SERIAL PRIMARY KEY,
    name VARCHAR(30),
    age INT DEFAULT 0);

INSERT INTO students (name, age)
VALUES ('PETR PETROV',22),
('IVAN IVANOV',21),
('ANNA SIDOROVA',18);