server:
  port: 8080
  servlet:
    context-patch: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lesson_7
    username: gb_user
    password: gb_user
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
